version: '3.9'

services:
  bot:
    build:
      context: .
    command: python run.py
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=sqlite:///data/casino.db
    volumes:
      - ./data:/app/data
      - ./:/app
